[package]
name = "zeke"
version = "0.5.1"
authors = ["Nick Willett-Jeffries <hello@nwj.cc>"]
edition = "2018"
description = "Zeke is a CLI for managing a knowledge base built on a local folder of plain text Markdown files."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "^0.4.19", features = ["serde"] }
clap = "^2.33.2"
regex = "^1.4.4"
serde = { version = "^1.0.124", features = ["derive"] }
serde_yaml = "^0.8.17"
pulldown-cmark = { version = "^0.8.0", default-features = false, features = ["simd"] }
pulldown-cmark-to-cmark = "^6.0.0"
path-clean = "^0.1.0"
anyhow = "^1.0.38"
ignore="^0.4.17"
rayon = "^1.5.0"
shell-words = "^1.0.0"

[dev-dependencies]
assert_cmd = "^1.0.3"
assert_fs = "^1.0.1"
predicates = "^1.0.7"
proptest = "^1.0.0"
