[package]
name = "zeke"
version = "0.4.2"
authors = ["Nick Willett-Jeffries <hello@nwj.cc>"]
edition = "2018"
description = "Zeke is a CLI for managing a personal note archive of plain text markdown files"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "^0.4.13", features = ["serde"] }
clap = "^2.33.2"
regex = "^1.3.9"
serde = { version = "^1.0.114", features = ["derive"] }
serde_yaml = "^0.8.13"
petgraph = "^0.5.1"
pulldown-cmark = { version = "^0.7.2", default-features = false, features = ["simd"] }
pulldown-cmark-to-cmark = "^5.0.0"
path-clean = "^0.1.0"
anyhow = "^1.0.32"

[dev-dependencies]
assert_cmd = "^1.0.1"
assert_fs = "^1.0.0"
predicates = "^1.0.5"
proptest = "^0.10.0"
