[package]
name = "zeke"
version = "0.2.0"
authors = ["Nick Willett-Jeffries <hello@nwj.cc>"]
edition = "2018"
description = "A tool for managing notes using the 'zettelkasten' system"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "~0.4.10", features = ["serde"] }
clap = "~2.33.0"
regex = "~1.3.4"
serde = { version = "~1.0.104", features = ["derive"] }
serde_yaml = "~0.8.11"

[dev-dependencies]
assert_cmd = "~0.12.0"
assert_fs = "~0.13.1"
predicates = "~1.0.3"
proptest = "~0.9.5"
