[package]
name = "zeke"
version = "0.1.0"
authors = ["Nick Willett-Jeffries <nwillettjeffries@gmail.com>"]
edition = "2018"
description = "A tool for managing notes using the 'zettelkasten' system"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.33.0"

[dev-dependencies]
assert_cmd = "~0.12.0"
predicates = "~1.0.3"
